// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAskgfahl8F_L7KnhCkxLneO4_PNu-gMWs',
    appId: '1:299177190445:web:782dd876831486fc5d04a4',
    messagingSenderId: '299177190445',
    projectId: 'factory-manager-f2979',
    authDomain: 'factory-manager-f2979.firebaseapp.com',
    storageBucket: 'factory-manager-f2979.appspot.com',
    measurementId: 'G-VR7NKXYXGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVO8GGQ_F9ckbNkbrgcK0zm1J-ToD1rCs',
    appId: '1:299177190445:android:6bc35fec1e8ca1165d04a4',
    messagingSenderId: '299177190445',
    projectId: 'factory-manager-f2979',
    storageBucket: 'factory-manager-f2979.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7xojO7WrITjXiNwYe6JtA8YhUm6UgeVA',
    appId: '1:299177190445:ios:c4eee2208aed17cc5d04a4',
    messagingSenderId: '299177190445',
    projectId: 'factory-manager-f2979',
    storageBucket: 'factory-manager-f2979.appspot.com',
    iosBundleId: 'com.example.factoryManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7xojO7WrITjXiNwYe6JtA8YhUm6UgeVA',
    appId: '1:299177190445:ios:c4eee2208aed17cc5d04a4',
    messagingSenderId: '299177190445',
    projectId: 'factory-manager-f2979',
    storageBucket: 'factory-manager-f2979.appspot.com',
    iosBundleId: 'com.example.factoryManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAskgfahl8F_L7KnhCkxLneO4_PNu-gMWs',
    appId: '1:299177190445:web:c5a8c7a5dc7fab645d04a4',
    messagingSenderId: '299177190445',
    projectId: 'factory-manager-f2979',
    authDomain: 'factory-manager-f2979.firebaseapp.com',
    storageBucket: 'factory-manager-f2979.appspot.com',
    measurementId: 'G-TX2PH64VX1',
  );
}
